---
- name: Deploy server
  hosts: deploy
  roles:
    - preconfig
    # - deploy
    # - swarm_init

- name: Managers
  hosts: managers
  roles:
    - preconfig
    # - swarm_join

- name: Workers
  hosts: workers
  roles:
    - preconfig
    # - swarm_join
