---
- name: Deploy server
  hosts: deploy
  roles:
    - role: preconfig
      tags: preconfig
    - role: deploy
      deploy_test: 0
      tags: deploy
    # - deploy
    # - swarm_init

- name: Managers
  hosts: managers
  roles:
    - role: preconfig
      tags: preconfig
    # - swarm_join

- name: Workers
  hosts: workers
  roles:
    - role: preconfig
      tags: preconfig
    # - swarm_join
