---
- name: Preconfig
  hosts: demo
  become: true
  tasks:
    - name: Установка необходимых пакетов для Docker
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        update_cache: true
        cache_valid_time: 86400

    - name: Создать директорию для ключей Docker
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Добавление ключа Docker
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Установка стабильного репозитория Docker
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] \
          https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        update_cache: true

    - name: Установка Docker и плагинов
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: true

    - name: Запуск и включение сервиса Docker
      ansible.builtin.service:
        name: docker
        state: restarted
        enabled: true

    - name: Добавление пользователя в группу Docker
      ansible.builtin.user:
        name: '{{ ansible_user }}'
        groups: docker
        append: true

    - name: Перезагрузка сервера
      ansible.builtin.reboot:
