galaxy_info:
  role_name: deploy
  description: Выкладка микросервисов на docker кластер
  author: Maksim
  license: MIT
  min_ansible_version: '2.18'
  platforms:
    - name: Ubuntu
      versions:
        - all
